language: python
python:
  - '2.7'
  - '3.2'
script:
  - curl -o travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
after_success: 
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then 
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "PUBLISHING..." 
        else 
          echo "No Publish!" 
        fi
      fi
after_failure:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then 
        if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then 
          echo "All Failed" 
        else 
          echo "Some Failed"
        fi
      fi
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS