language: python
python:
  - '2.7'
  - '3.2'
script:
  - curl -o travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
after_success: 
  - python travis_after_all.py
  - echo $BUILD_LEADER $BUILD_AGGREGATE_STATUS
  - export AGGREGATE_STATUS=$BUILD_AGGREGATE_STATUS
after_failure:
  - python travis_after_all.py
  - echo $BUILD_LEADER $BUILD_AGGREGATE_STATUS
  - export AGGREGATE_STATUS=$BUILD_AGGREGATE_STATUS
after_script:
  - echo $AGGREGATE_STATUS